# 📊 Análise de Vendas com Pandas

## 🎯 Objetivo

Realizar uma análise exploratória dos dados de vendas utilizando Python e Pandas, buscando compreender o comportamento das vendas e identificar padrões, tendências e informações relevantes para o negócio.

## 🔎 O que será analisado?

- Faturamento total
- Quantidade de pedidos
- Ticket médio
- Evolução das vendas ao longo do tempo
- Vendas por categoria
- Vendas por segmento
- Vendas por região
- Produtos com maior volume de vendas
- Períodos com maior e menor desempenho
- Principais tendências e padrões encontrados nos dados

# 1. Importação das Bibliotecas

In [1]:
import pandas as pd

# 2. Carregamento dos Dados

In [2]:
base = pd.read_csv("../data/raw/train.csv")

# 3. Conhecendo os Dados

In [3]:
base.head()

,ID da Linha,ID do Pedido,Data do Pedido,Data de Envio,Modo de Envio,ID do Cliente,Nome do Cliente,Segmento,País,Cidade,Estado,CEP,Região,ID do Produto,Categoria,Subcategoria,Nome do Produto,Vendas
0,1,CA-2017-152156,08/11/2017,11/11/2017,Segunda Classe,CG-12520,Claire Gute,Consumidor,Estados Unidos,Henderson,Kentucky,42420.0,Sul,FUR-BO-10001798,Móveis,Estantes,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Segunda Classe,CG-12520,Claire Gute,Consumidor,Estados Unidos,Henderson,Kentucky,42420.0,Sul,FUR-CH-10000454,Móveis,Cadeiras,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Segunda Classe,DV-13045,Darrin Van Huff,Corporativo,Estados Unidos,Los Angeles,Califórnia,90036.0,Oeste,OFF-LA-10000240,Material de Escritório,Etiquetas,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Classe Padrão,SO-20335,Sean O'Donnell,Consumidor,Estados Unidos,Fort Lauderdale,Flórida,33311.0,Sul,FUR-TA-10000577,Móveis,Mesas,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Classe Padrão,SO-20335,Sean O'Donnell,Consumidor,Estados Unidos,Fort Lauderdale,Flórida,33311.0,Sul,OFF-ST-10000760,Material de Escritório,Armazenamento,Eldon Fold 'N Roll Cart System,22.3680

In [4]:
base.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID da Linha      9800 non-null   int64
 1   ID do Pedido     9800 non-null   str
 2   Data do Pedido   9800 non-null   str
 3   Data de Envio    9800 non-null   str
 4   Modo de Envio    9800 non-null   str
 5   ID do Cliente    9800 non-null   str
 6   Nome do Cliente  9800 non-null   str
 7   Segmento         9800 non-null   str
 8   País             9800 non-null   str
 9   Cidade           9800 non-null   str
 10  Estado           9800 non-null   str
 11  CEP              9789 non-null   float64
 12  Região           9800 non-null   str
 13  ID do Produto    9800 non-null   str
 14  Categoria        9800 non-null   str
 15  Subcategoria     9800 non-null   str
 16  Nome do Produto  9800 non-null   str
 17  Vendas           9800 non-null   float64
dtypes: float64(2), int64(1), str(15)
memory usage: 1.3 MB

In [5]:
base.describe()

       ID da Linha           CEP        Vendas
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

# 4. Qualidade dos Dados

In [6]:
base.isnull().sum()

ID da Linha         0
ID do Pedido        0
Data do Pedido      0
Data de Envio       0
Modo de Envio       0
ID do Cliente       0
Nome do Cliente     0
Segmento            0
País                0
Cidade              0
Estado              0
CEP                11
Região              0
ID do Produto       0
Categoria           0
Subcategoria        0
Nome do Produto     0
Vendas              0
dtype: int64

In [7]:
base.duplicated().sum()

np.int64(0)

# 5. Tratamento dos Dados

In [8]:
base["Data do Pedido"] = pd.to_datetime(base["Data do Pedido"], format="%d/%m/%Y")

In [9]:
base["Data de Envio"] = pd.to_datetime(base["Data de Envio"], format="%d/%m/%Y")

In [10]:
base.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID da Linha      9800 non-null   int64
 1   ID do Pedido     9800 non-null   str
 2   Data do Pedido   9800 non-null   datetime64[us]
 3   Data de Envio    9800 non-null   datetime64[us]
 4   Modo de Envio    9800 non-null   str
 5   ID do Cliente    9800 non-null   str
 6   Nome do Cliente  9800 non-null   str
 7   Segmento         9800 non-null   str
 8   País             9800 non-null   str
 9   Cidade           9800 non-null   str
 10  Estado           9800 non-null   str
 11  CEP              9789 non-null   float64
 12  Região           9800 non-null   str
 13  ID do Produto    9800 non-null   str
 14  Categoria        9800 non-null   str
 15  Subcategoria     9800 non-null   str
 16  Nome do Produto  9800 non-null   str
 17  Vendas           9800 non-null   float64
dtypes: datetime64[us](2), float64(2), int64(1), str(13)
memory usage: 1.3 MB

In [11]:
base = base.dropna(subset=["CEP"])

# 6. Análise Exploratória

In [ ]:
faturamento_total = base["Vendas"].sum()
print(f"Faturamento total: US$ {faturamento_total:.2f}")

Faturamento total: R$ 2252607.41

In [13]:
quantidade_pedidos = base["ID do Pedido"].nunique()
print(f"Quantidade de pedidos: {quantidade_pedidos}")

Quantidade de pedidos: 4916

In [14]:
ticket_medio = faturamento_total / quantidade_pedidos
print(f"Ticket Médio: {ticket_medio:.2f}")

Ticket Médio: 458.22

In [ ]:
vendas_por_categoria = (
    base.groupby("Categoria")["Vendas"].sum().sort_values(ascending=False)
)
print("\nVendas Por Categoria:")
print(vendas_por_categoria)

Vendas Por Categoria:
Categoria
Tecnologia                825856.1130
Móveis                    723538.4757
Material de Escritório    703212.8240
Name: Vendas, dtype: float64

In [38]:
quantidade_por_categoria = base["Categoria"].value_counts()
print("\nQuantidade Vendida por Categoria:")
print(quantidade_por_categoria)

Quantidade Vendida por Categoria:
Categoria
Material de Escritório    5903
Móveis                    2076
Tecnologia                1810
Name: count, dtype: int64

In [ ]:
vendas_por_segmento = (
    base.groupby("Segmento")["Vendas"].sum().sort_values(ascending=False)
)
print("\nVendas por Segmento:")
print(vendas_por_segmento)

Vendas por Segmento:
Segmento
Consumidor     1.146708e+06
Corporativo    6.822118e+05
Home Office    4.236874e+05
Name: Vendas, dtype: float64

In [36]:
vendas_por_região = base.groupby("Região")["Vendas"].sum().sort_values(ascending=False)
print("\nVendas por Região:")
print(vendas_por_região)

Vendas por Região:
Região
Oeste      710219.6845
Leste      660589.3560
Central    492646.9132
Sul        389151.4590
Name: Vendas, dtype: float64

In [23]:
volume_por_produto = base["Nome do Produto"].value_counts()
print("\nProdutos com maior volume de vendas:")
print(volume_por_produto)

Produtos com maior volume de vendas:
Nome do Produto
Staple envelope                                 47
Staples                                         46
Easy-staple paper                               44
Avery Non-Stick Binders                         20
Staple remover                                  18
                                                ..
Sony 8GB Class 10 Micro SDHC R40 Memory Card     1
RCA ViSYS 25425RE1 Corded phone                  1
Cisco 8961 IP Phone Charcoal                     1
Eureka Hand Vacuum, Bagless                      1
LG G2                                            1
Name: count, Length: 1848, dtype: int64

In [ ]:
faturamento_por_mes = base.groupby(base["Data do Pedido"].dt.to_period("M"))[
    "Vendas"
].sum()

In [ ]:
periodo_maior_faturamento = faturamento_por_mes.idxmax()
maior_faturamento = faturamento_por_mes.max()
print(f"Maior faturamento: {periodo_maior_faturamento} | US$ {maior_faturamento:.2f}")

Maior faturamento: 2018-11 | R$ 117938.15

In [ ]:
periodo_menor_faturamento = faturamento_por_mes.idxmin()
menor_faturamento = faturamento_por_mes.min()
print(f"Menor faturamento: {periodo_menor_faturamento} | US$ {menor_faturamento:.2f}")

Menor faturamento: 2015-02 | R$ 4519.89

## Principais Tendências e Padrões Identificados

Após a limpeza, o tratamento e a análise exploratória dos dados, foram identificados os seguintes resultados:

### Indicadores Gerais

- **Faturamento total:** US$ 2.252.607,41
- **Quantidade de pedidos:** 4.916
- **Ticket médio:** US$ 458,22

### Desempenho por Categoria

A categoria **Tecnologia** apresentou o maior faturamento, com aproximadamente **US$ 825,9 mil**, seguida por Móveis e Material de Escritório.

Apesar de possuir o menor número de registros de venda entre as categorias, Tecnologia apresentou o maior faturamento. Em contrapartida, **Material de Escritório** possui o maior número de registros, mas o menor faturamento entre as três categorias.

Esse comportamento indica que as vendas da categoria Tecnologia possuem, em média, valores mais elevados.

### Desempenho por Região

A região **Oeste** apresentou o maior valor de vendas, com aproximadamente **US$ 710,2 mil**.

Em seguida aparecem as regiões Leste, Central e Sul. A região **Sul** apresentou o menor faturamento, com aproximadamente **US$ 389,2 mil**.

### Produtos com Maior Volume de Registros

Os produtos que apareceram com maior frequência nos registros de venda foram:

1. Staple envelope — 47 registros
2. Staples — 46 registros
3. Easy-staple paper — 44 registros

Como a base não possui uma coluna de quantidade de unidades, esses valores representam a frequência dos produtos nos registros de venda, e não a quantidade de unidades comercializadas.

### Desempenho ao Longo do Tempo

O período de **maior faturamento** foi **novembro de 2018**, com **US$ 117.938,15**.

O período de **menor faturamento** foi **fevereiro de 2015**, com **US$ 4.519,89**.

### Conclusão

A análise mostrou diferenças importantes entre volume de registros e faturamento. Tecnologia, mesmo aparecendo com menor frequência entre as categorias, apresentou o maior faturamento, enquanto Material de Escritório apresentou comportamento inverso.

Também foi identificada uma diferença relevante no desempenho entre regiões e períodos, que poderá ser explorada visualmente no dashboard desenvolvido no Power BI.

In [39]:
base.to_csv("base_tratada.csv", index=False)